# Generated by Django 2.1.1 on 2018-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='content_img')),
                ('name', models.CharField(max_length=20)),
                ('pub_time', models.DateTimeField(verbose_name='data published')),
            ],
        ),
        migrations.CreateModel(
            name='Style_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='style_img')),
                ('name', models.CharField(max_length=20)),
                ('pub_time', models.DateTimeField(verbose_name='data published')),
            ],
        ),
        migrations.DeleteModel(
            name='IMG',
        ),
    ]
